In [112]:
import pandas as pd
import numpy as np

In [113]:
df = pd.read_csv("/kaggle/input/insurance/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [114]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer

In [115]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [116]:
categorical_cols_Ordinal = ['smoker']
categorical_cols_Nominal = ['sex', 'region']
numeric_cols = ['age', 'bmi', 'children']

In [117]:
numeric_pipe = Pipeline([
    ('transformer', PowerTransformer())
])

In [118]:
categorical_pipe_Nominal = Pipeline([
    ('one hot', OneHotEncoder(sparse_output=False, drop = 'first')),
])

In [119]:
categorial_pipe_Ordinal = Pipeline([
    ('Ordinal', OrdinalEncoder(categories = [['yes', 'no']]))
])

In [120]:
preprocessor = ColumnTransformer([
    ('Ncat', categorical_pipe_Nominal, categorical_cols_Nominal),
    ('Ocat', categorial_pipe_Ordinal, categorical_cols_Ordinal),
    ('numeric', numeric_pipe, numeric_cols),
], remainder = 'passthrough')

In [121]:
pipe = Pipeline([
    ('Preprocessing', preprocessor),
    ('training', LinearRegression())
])

In [122]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [123]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['charges']), df['charges'], test_size = 0.25)

In [124]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Ncat',
                                                  Pipeline(steps=[('one hot',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  ['sex', 'region']),
                                                 ('Ocat',
                                                  Pipeline(steps=[('Ordinal',
                                                                   OrdinalEncoder(categories=[['yes',
                                                                                               'no']]))]),
                                                  ['smoker']),
                                                 ('numeric',
                                                  Pipeline(steps=[('transformer',
                                                                   PowerTransformer())]),
                                                  ['age', 'bmi',
                                                   'children'])])),
                ('training', LinearRegression())])

In [125]:
y_pred = pipe.predict(X_test)

In [126]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

print("\nTEST")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R²  :", r2_score(y_test, y_pred))

TEST
MAE : 4370.684756856249
RMSE: 6148.019806456462
R²  : 0.7252441330801718

In [127]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010