In [3]:
import numpy as np 
import pandas as pd 

number = np.random.randint(1, 10, n)

df = pd.DataFrame({
    "Cabin": [
        f"{np.random.choice(['A', 'B', 'C', 'D', 'E', 'F'])}{np.random.randint(1, 100)}"
        for _ in range(n)
    ],

    "Ticket": [
        f"TKT{np.random.randint(10000, 99999)}"
        for _ in range(n)
    ],

    "number": number,

    "Survived": [
        np.random.randint(0, x + 1)
        for x in number
    ]
})

In [6]:
df.head()

  Cabin    Ticket  number  Survived
0   F76  TKT89104       1         0
1    D8  TKT69399       7         3
2   B92  TKT89714       7         0
3   D90  TKT60428       9         3
4   B60  TKT97731       3         0

In [8]:
df['Cabin_No'] = df['Cabin'].str.extract(r'(\d+)')

In [9]:
df.head()

  Cabin    Ticket  number  Survived Cabin_No
0   F76  TKT89104       1         0       76
1    D8  TKT69399       7         3        8
2   B92  TKT89714       7         0       92
3   D90  TKT60428       9         3       90
4   B60  TKT97731       3         0       60

In [11]:
df['Cabin_Cat'] = df['Cabin'].str[0]

In [12]:
df.head()

  Cabin    Ticket  number  Survived Cabin_No Cabin_Cat
0   F76  TKT89104       1         0       76         F
1    D8  TKT69399       7         3        8         D
2   B92  TKT89714       7         0       92         B
3   D90  TKT60428       9         3       90         D
4   B60  TKT97731       3         0       60         B

In [13]:
df['Tkt_no'] = df['Ticket'].str.extract(r'(\d+)')

In [14]:
df.head()

  Cabin    Ticket  number  Survived Cabin_No Cabin_Cat Tkt_no
0   F76  TKT89104       1         0       76         F  89104
1    D8  TKT69399       7         3        8         D  69399
2   B92  TKT89714       7         0       92         B  89714
3   D90  TKT60428       9         3       90         D  60428
4   B60  TKT97731       3         0       60         B  97731

In [17]:
df['Tkt_Cat'] = df['Ticket'].str[0:3]

In [18]:
df.head()

  Cabin    Ticket  number  Survived Cabin_No Cabin_Cat Tkt_no Tkt_Cat
0   F76  TKT89104       1         0       76         F  89104     TKT
1    D8  TKT69399       7         3        8         D  69399     TKT
2   B92  TKT89714       7         0       92         B  89714     TKT
3   D90  TKT60428       9         3       90         D  60428     TKT
4   B60  TKT97731       3         0       60         B  97731     TKT