In [4]:
import numpy as np
import pandas as pd

np.random.seed(42)

# 1 year of dates
dates = pd.date_range(
    start="2025-01-01",
    end="2025-12-31",
    freq="D"
)

n = len(dates)

df = pd.DataFrame({
    "Date": dates
})


# ---------------------------------------
# Generate realistic daily expenses
# ---------------------------------------

# Base daily spending
amount = np.random.gamma(
    shape=2.5,
    scale=350,
    size=n
)

# Weekend spending tends to be higher
is_weekend = df["Date"].dt.dayofweek >= 5

amount[is_weekend] *= np.random.uniform(
    1.1, 1.5, is_weekend.sum()
)


# ---------------------------------------
# Add some random large expenses
# ---------------------------------------

large_expense_days = np.random.choice(
    n,
    size=15,
    replace=False
)

amount[large_expense_days] += np.random.randint(
    2000,
    10000,
    size=len(large_expense_days)
)


# ---------------------------------------
# Add monthly fixed expense
# ---------------------------------------

for month in range(1, 13):

    month_indices = df.index[
        df["Date"].dt.month == month
    ]

    # Random day within the month
    idx = np.random.choice(month_indices)

    amount[idx] += np.random.randint(
        8000,
        15000
    )


# Round amounts
df["Amount"] = np.round(amount, 2)


# ---------------------------------------
# Shuffle rows
# ---------------------------------------

df = df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

        Date   Amount
0 2025-07-13   950.20
1 2025-02-03  1119.13
2 2025-01-16   816.93
3 2025-11-06  1137.20
4 2025-02-27   601.74
5 2025-07-03  1268.02
6 2025-03-18   353.93
7 2025-04-30   280.57
8 2025-06-02  1424.30
9 2025-05-07  1055.82

Shape: (365, 2)

In [5]:
df.sample(3)

          Date   Amount
143 2025-07-02   658.86
361 2025-04-17   765.05
236 2025-08-10  3474.46

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    365 non-null    datetime64[us]
 1   Amount  365 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 5.8 KB

In [7]:
df['Is_Weekend'] = df['Date'].dt.dayofweek >= 5

In [8]:
df.head()

        Date   Amount  Is_Weekend
0 2025-07-13   950.20        True
1 2025-02-03  1119.13       False
2 2025-01-16   816.93       False
3 2025-11-06  1137.20       False
4 2025-02-27   601.74       False

In [12]:
pd.pivot_table(
    data = df,
    index = 'Is_Weekend',
    values = 'Amount',
    aggfunc = ['mean'],
)

                   mean
                 Amount
Is_Weekend
False       1597.976169
True        1444.504808

In [13]:
df['Date'].dt.year

0      2025
1      2025
2      2025
3      2025
4      2025
       ...
360    2025
361    2025
362    2025
363    2025
364    2025
Name: Date, Length: 365, dtype: int32

In [14]:
df['Date'].dt.month

0       7
1       2
2       1
3      11
4       2
       ..
360     3
361     4
362     9
363    12
364     4
Name: Date, Length: 365, dtype: int32

In [16]:
df['Date'].dt.month_name()

0           July
1       February
2        January
3       November
4       February
         ...
360        March
361        April
362    September
363     December
364        April
Name: Date, Length: 365, dtype: str

In [17]:
df['Date'].dt.day_name()

0        Sunday
1        Monday
2      Thursday
3      Thursday
4      Thursday
         ...
360    Thursday
361    Thursday
362      Sunday
363      Monday
364      Sunday
Name: Date, Length: 365, dtype: str

# Cheat Sheet

In [18]:
# Convert to datetime
pd.to_datetime(dF["Date"])

# Date components
dF["Date"].dt.date
df["Date"].dt.year
df["Date"].dt.month
df["Date"].dt.day
df["Date"].dt.hour
df["Date"].dt.minute
df["Date"].dt.second
df["Date"].dt.microsecond
df["Date"].dt.nanosecond

# Day information
df["Date"].dt.dayofweek
df["Date"].dt.day_of_week
df["Date"].dt.day_name()
df["Date"].dt.days_in_month

# Week information
df["Date"].dt.isocalendar().week
df["Date"].dt.isocalendar().year
df["Date"].dt.isocalendar().day

# Month information
df["Date"].dt.month
df["Date"].dt.month_name()
df["Date"].dt.days_in_month
df["Date"].dt.is_month_start
df["Date"].dt.is_month_end

# Quarter information
df["Date"].dt.quarter
df["Date"].dt.is_quarter_start
df["Date"].dt.is_quarter_end

# Year information
df["Date"].dt.is_year_start
df["Date"].dt.is_year_end

# Timezone information
df["Date"].dt.tz
df["Date"].dt.tz_localize("UTC")
df["Date"].dt.tz_convert("Asia/Kolkata")

# Formatting
df["Date"].dt.strftime("%d-%m-%Y")
df["Date"].dt.strftime("%Y-%m-%d")
df["Date"].dt.strftime("%B %Y")
df["Date"].dt.strftime("%A")

# Normalize time to midnight
df["Date"].dt.normalize()

# Timezone / UTC
df["Date"].dt.tz_localize(None)
df["Date"].dt.tz_convert("UTC")

# Period conversion
df["Date"].dt.to_period("M")
df["Date"].dt.to_period("W")
df["Date"].dt.to_period("Q")
df["Date"].dt.to_period("Y")

# Timedelta operations
df["Date"].diff()
df["Date"].diff().dt.days
df["Date"].diff().dt.seconds
df["Date"].diff().dt.total_seconds()

# Date arithmetic
df["Date"] + pd.Timedelta(days=7)
df["Date"] - pd.Timedelta(days=7)

# Date range
pd.date_range("2025-01-01", "2025-12-31")
pd.date_range("2025-01-01", periods=365, freq="D")

# Sorting
df.sort_values("Date")

# Resampling
df.set_index("Date")
df["Amount"].resample("D").sum()
df["Amount"].resample("W").sum()
df["Amount"].resample("ME").sum()
df["Amount"].resample("QE").sum()
df["Amount"].resample("YE").sum()

# Date-based indexing
df.loc["2025-01"]
df.loc["2025-01-01":"2025-01-31"]

# Common derived features
df["Is_Weekend"] = df["Date"].dt.dayofweek >= 5
df["Is_Weekday"] = df["Date"].dt.dayofweek < 5
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day
df["Day_Name"] = df["Date"].dt.day_name()
df["Quarter"] = df["Date"].dt.quarter
df["Week"] = df["Date"].dt.isocalendar().week

NameError: name 'dF' is not defined

In [22]:
import pandas as pd


def add_date_features(df, col) -> pd.DataFrame:
    df = df.copy()

    date_col = df[col]

    df["Is_Weekend"] = date_col.dt.dayofweek >= 5
    df["Is_Weekday"] = date_col.dt.dayofweek < 5
    df["Year"] = date_col.dt.year
    df["Month"] = date_col.dt.month
    df["Month_Name"] = date_col.dt.month_name()
    df["Day"] = date_col.dt.day
    df["Day_Name"] = date_col.dt.day_name()
    df["Quarter"] = date_col.dt.quarter
    df["Week"] = date_col.dt.isocalendar().week

    return df

In [28]:
df2 = add_date_features(df, "Date")

In [29]:
df2.head()

,Date,Amount,Is_Weekend,Is_Weekday,Year,Month,Month_Name,Day,Day_Name,Quarter,Week
0,2025-07-13,950.20,True,False,2025,7,July,13,Sunday,3,28
1,2025-02-03,1119.13,False,True,2025,2,February,3,Monday,1,6
2,2025-01-16,816.93,False,True,2025,1,January,16,Thursday,1,3
3,2025-11-06,1137.20,False,True,2025,11,November,6,Thursday,4,45
4,2025-02-27,601.74,False,True,2025,2,February,27,Thursday,1,9